- _2023/February/Limelight 2023.md
- _2023/collection.yml
- _about-cgs/Admission/Information on Direct School Admission to Crescent Girls' School.md
New updates for the school website:
- What's Happening article
- Information on Direct school admission to Crescent Girls School.
> New school website update

- _about-cgs/Admission/Information on Direct School Admission to Crescent Girls' School.md
…escent Girls' School.md","fileName":"Information on Direct School Admission to Crescent Girls' School.md","userId":"1176"}
> Small update 

- _about-cgs/Admission/Information on Direct School Admission to Crescent Girls' School.md
I've reupdate the information once gain.
> Reupdate on Direct school admission webpage

- _2022/collection.yml
- _2023/April/International Friendship Day 2023.md
- _2023/collection.yml
- _about-cgs/Admission/Information on Direct School Admission to Crescent Girls' School.md
Isomer has helped to update the following:
~ Information on Direct School Admission to CGS
I have updated the following:
~ Whats happening (article)
> Updates on school website

- _about-cgs/Supplier.md
- _about-cgs/collection.yml
I have updated the following information:
- Supplier (Available in "About CGS")
> New Update on Supplier

- _about-cgs/Calender of Events.md
I have re-updated the school website calendar.
> Update on School Website Calendar

- _2023/July/Swift Explorers Singapore 2023.md
- _2023/June/Model United Nations Conference 2023.md
- _2023/June/Student Leaders’ Investiture 2023.md
- _2023/collection.yml
New update on the following:
What's Happening!
- June
Model United Nations Conference 2023
Student Leaders’ Investiture 2023
- July
SES 2023
> New Update on What's Happening

- _2023/July/National Schools Literature Festival 2023.md
- _2023/collection.yml
- _about-cgs/Admission/Open House 2023.md
- _about-cgs/collection.yml
- _our-partners/School Advisory Committee.md
New Update on the following:
What's happening in July 2023
- National School Literature Festival 2023
Our Partner
- School Advisory: Mrs Chong (Principal name)
> School website update

- _about-cgs/Admission/Admission after PSLE.md
- Updated cut off points for Q1: What is the school cut-off PSLE
- Changed year for Q2 to 2024 Secondary One Posting Exercise
- Updated Application period dates
> Update Admission after PSLE Page

- _about-cgs/Admission/Secondary 1 Registration 2023.md
- pages/New Announcements.md
Created link to Sec 1 Orientation Page in New Announcement
> Updated New Announcement Page

- _2024/February/Total Defence Day 2024.md
- _2024/collection.yml
- _about-cgs/Calender of Events.md
2 School website update:
- School Calendar
- What's Happening
> School website udpate

- _cca/Performing Arts/Choir.md
- _data/navigation.yml
New updates on the following:
- Whats happening for the month of July
- Choir CCA information
- Symphony Band CCA information
> School Website New update

- _our-people/Organisational Chart.md
New updates on the following:
- School Organisation Chart
> New Updates

- _about-cgs/Admission/Transfer of School.md
Minor Update on the following webpage:
- Transfer of school
> Minor Update

- _about-cgs/School Canteen Advertisement/Indian Vegetarian Stall.md
- _about-cgs/School Canteen Advertisement/Muslim Stall.md
Updates on canteen advertisement
> Canteen advertisement

- _about-cgs/Admission/Admission after PSLE.md
Reupload the link for the appeal form in Admission after PSLE
> Reupdate on admission

- _about-cgs/Admission/Admission after PSLE.md
Update Cut off points for Admission after PSLE
> Update Cut off points for Admission after PSLE

- _sec-1-registration-2024/Briefing Videos.md
- _sec-1-registration-2024/Sec 1 Registration: Welcome Annoucements.md
edited "Higher Demanding Level" to the correct "More Demanding Level"
> Sec 1 registration page

- _sec-1-registration-2024/Higher MTL, 3rd Language, MEP and Option to Take Subjects at G3 Level.md
changed MEP registration deadline to 26 Dec
> sec 1 registration

- _our-holistic-curriculum/Character and Citizenship Edu/Sexuality Education.md
Updates on the following:
- Sexuality Education page
> New Update school website

- _about-cgs/School Canteen Advertisement/Indian Vegetarian Stall.md
- _about-cgs/School Canteen Advertisement/Muslim Stall.md
Update on Canteen advertisement closing date
> Canteen advertisement may2025

- _2025/April/Hari Raya Celebrations@CGS.md
- _2025/collection.yml
- _our-people/Departments/Student Development Team.md
Update on Student Development Teams
> update in School Website

- _cradle/National Sustainability Moveme/One Earth Symposium (OES).md
A new update on the registration link and deadline is at the bottom of the page.
> NSM: One Earth Symposium (OES) registration update

- _our-people/Organisational Chart.md
> VPA NAME IN SCHOOL WEBSITE

- _data/navigation.yml
> Link to Canteen advertisement

- _cca/Performing Arts/Choir.md
- _cca/Performing Arts/English Drama.md
> New Update on Choir
